# Generated by Django 4.2.19 on 2025-02-21 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(db_column='id', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(db_column='id', max_length=255, primary_key=True, serialize=False)),
                ('email', models.CharField(db_column='email', max_length=255, unique=True)),
                ('password', models.CharField(db_column='password', max_length=255)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.CharField(db_column='id', max_length=255, primary_key=True, serialize=False)),
                ('created_by', models.CharField(db_column='created_by', max_length=255)),
                ('category_name', models.CharField(db_column='category_name', max_length=255)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('url', models.CharField(db_column='url', max_length=255)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='auroraworld.category')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='auroraworld.user')),
            ],
            options={
                'db_table': 'links',
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.CharField(db_column='id', max_length=255, primary_key=True, serialize=False)),
                ('user_email', models.CharField(db_column='user_email', max_length=255)),
                ('is_writable', models.BooleanField(db_column='is_writable', default=False)),
                ('link', models.ForeignKey(db_column='link_id', on_delete=django.db.models.deletion.CASCADE, to='auroraworld.link')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='auroraworld.user')),
            ],
            options={
                'db_table': 'shares',
                'unique_together': {('link', 'user')},
            },
        ),
    ]
